app:
  api:
    version: 1.0
    title: User management API
    description: ^project.description^
    latest-prefix-endpoint: /api/v${app.api.version}

server:
  port: 9090

springdoc:
  swagger-ui:
    path: /api-docs.html
    show-extensions: true
    show-common-extensions: true

